// Copyright (C) 2026 George Sapkin
//
// SPDX-License-Identifier: GPL-3.0-only

import { Button, VerticalBox, HorizontalBox, Palette } from "std-widgets.slint";

export component AboutDialog inherits Rectangle {
    in property <string> version;

    in-out property <bool> show;

    property <float> open-progress: show ? 1.0 : 0.0;

    visible: open-progress > 0.01;
    background: rgba(0, 0, 0, 0.4 * open-progress);

    animate open-progress {
        duration: 250ms;
        easing: ease-in-out;
    }

    changed show => {
        if (show) {
            scope.focus()
        }
    }

    // Block events to underlying UI and provide light-dismiss (click outside
    // to close)
    TouchArea {
        clicked => {
            root.show = false;
        }
    }

    forward-focus: scope;

    scope := FocusScope {
        KeyBinding {
            keys: @keys(Escape);
            activated => {
                root.show = false;
            }
        }

        Rectangle {
            width: 400px;
            height: 450px;

            opacity: open-progress;
            transform-scale-x: 0.95 + (open-progress * 0.05);
            transform-scale-y: self.transform-scale-x;

            background: Palette.background;
            border-width: 1px;
            border-color: Palette.border;
            border-radius: 8px;

            drop-shadow-blur: 16px;
            drop-shadow-offset-y: 8px;
            drop-shadow-color: Palette.color-scheme == ColorScheme.dark ? rgba(0, 0, 0, 0.26) : rgba(0, 0, 0, 0.14);

            // Block events from falling through to the background dismiss area
            TouchArea { }

            VerticalBox {
                padding: 0px;
                padding-bottom: 8px;
                spacing: 10px;

                Rectangle {
                    background: Palette.control-background;
                    border-width: 1px;
                    border-color: Palette.border;
                    border-top-left-radius: 8px;
                    border-top-right-radius: 8px;
                    vertical-stretch: 1;

                    VerticalLayout {
                        padding: 20px;
                        spacing: 15px;
                        HorizontalBox {
                            alignment: center;
                            padding: 0;
                            Image {
                                source: @image-url("../assets/logo.svg");
                                width: 150px;
                                height: 150px;
                                horizontal-alignment: center;
                                image-rendering: pixelated;
                            }
                        }

                        VerticalBox {
                            padding: 0;
                            spacing: 5px;

                            Text {
                                text: "Bouwer";
                                font-size: 24px;
                                font-weight: 700;
                                horizontal-alignment: center;
                                color: Palette.foreground;
                            }

                            Text {
                                text: root.version;
                                color: Palette.foreground;
                                font-size: 14px;
                                horizontal-alignment: center;
                            }
                        }

                        Text {
                            text: "A simple interface for building custom OpenWrt firmware images using the official image builders.";
                            horizontal-alignment: center;
                            wrap: word-wrap;
                        }

                        Text {
                            text: "Copyright © 2026 George Sapkin";
                            horizontal-alignment: center;
                            wrap: word-wrap;
                        }

                        link_touch := TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                Platform.open-url("https://github.com/georgesapkin/bouwer");
                            }
                            Text {
                                text: "github.com/georgesapkin/bouwer";
                                color: link_touch.has-hover ? Palette.accent-background : Palette.foreground;
                                wrap: word-wrap;
                                horizontal-alignment: center;
                                animate color { duration: 100ms; }
                            }
                        }
                    }
                }

                HorizontalBox {
                    alignment: center;

                    close_button := Button {
                        text: "Close";
                        primary: true;
                        clicked => {
                            root.show = false;
                        }
                    }
                }
            }
        }
    }
}
