// Copyright (C) 2026 George Sapkin
//
// SPDX-License-Identifier: GPL-3.0-only

import {
    Button,
    ComboBox,
    GroupBox,
    HorizontalBox,
    LineEdit,
    ListView,
    Palette,
    ProgressIndicator,
    ScrollView,
    Switch,
    TabWidget,
    TextEdit,
    VerticalBox,
} from "std-widgets.slint";

import { AboutDialog } from "about.slint";
import { ImageBuilderItem, ImageBuilderList } from "builderlist.slint";
import { EditableComboBox } from "combobox.slint";
import { ImageButton } from "imagebutton.slint";
import { DeviceDialog } from "device.slint";
import { Notification } from "notification.slint";

global Constants {
    in-out property <length> autocomplete_element_height: 40px;
}

export struct AppState {
    build_command_preview: string,
    build_path_text: string,
    busy: bool,
    current_highlighted_profile_index: int,
    disabled_services_text: string,
    downloaded_builders: [ImageBuilderItem],
    extra_image_name_text: string,
    image_exists: bool,
    notification: string,
    notification_is_error: bool,
    notification_is_warning: bool,
    original_packages: [string],
    overlay_path_text: string,
    packages_text: string,
    profiles_fetch_failed: bool,
    profiles: [string],
    progress_value: float,
    progress_visible: bool,
    removed_packages_text: string,
    rootfs_size_text: string,
    search_text: string,
    selected_id: string,
    selected_model: string,
    selected_target: string,
    selected_version: string,
    show_about: bool,
    show_rcs: bool,
    show_device_dialog: bool,
    ssh_agent_identities: [string],
    status_text: string,
    version: string,
    versions: [string],
}

export struct BuildData {
    version: string,
    target: string,
    profile_id: string,
    extra_image_name: string,
    rootfs_size: int,
    packages: string,
    disabled_services: string,
    overlay_path: string,
}

export struct DownloadBuilderData {
    version: string,
    target: string,
    profile_id: string,
}

export struct DeleteBuilderData {
    tag: string,
    version: string,
    target: string,
    profile_id: string,
}

export struct FetchFromDeviceData {
    version: string,
    target: string,
    profile_id: string,
    host: string,
    user: string,
    identity: string,
    password: string,
}

export struct ProfileData {
    version: string,
    name: string,
}

export struct ProfileSearchKeyData {
    text: string,
    index: int,
    profiles: [string],
    version: string,
}

export struct ShowRcsData {
    version: string,
    show_rcs: bool,
}

export global StateBridge {
    in-out property <AppState> state: {
        current_highlighted_profile_index: -1,
    };

    callback build_path_edited(string);
    callback build_requested(BuildData);
    callback delete_builder_requested(DeleteBuilderData);
    callback download_builder_requested(DownloadBuilderData);
    callback fetch_from_device_requested(FetchFromDeviceData);
    callback fetch_ssh_agent_identities_requested();
    callback load_preset_requested(string);
    callback open_build_folder_requested(string);
    callback packages_edited(string);
    callback profile_search_edited(string);
    callback profile_search_key_pressed(ProfileSearchKeyData) -> bool;
    callback profile_selected(ProfileData);
    callback refresh_builders_requested();
    callback save_preset_requested(BuildData);
    callback select_build_folder_requested();
    callback select_overlay_folder_requested();
    callback show_rcs_toggled(ShowRcsData);
    callback update_build_preview(BuildData);
    callback version_changed(string);
}

export component AppWindow inherits Window {
    property <AppState> state <=> StateBridge.state;

    callback recalculate_preview();
    callback request_profile_search_focus();

    request_profile_search_focus => {
        profile_combo.focus();
    }

    recalculate_preview => {
        StateBridge.update_build_preview({
            version: root.state.selected_version,
            target: root.state.selected_target,
            profile_id: root.state.selected_id,
            extra_image_name: root.state.extra_image_name_text,
            rootfs_size: root.state.rootfs_size_text.to-float(),
            packages: root.state.packages_text,
            disabled_services: root.state.disabled_services_text,
            overlay_path: root.state.overlay_path_text,
        });
    }

    title: "Bouwer";
    icon: @image-url("../assets/logo_no_shadow.svg");
    min-width: 700px;
    min-height: 700px;
    preferred-height: 700px;

    DeviceDialog {
        show <=> root.state.show_device_dialog;
        identities: root.state.ssh_agent_identities;
        z: 1100;

        identities_requested() => {
            StateBridge.fetch_ssh_agent_identities_requested();
        }

        fetch_requested(host, user, password, identity) => {
            StateBridge.fetch_from_device_requested({
                version: root.state.selected_version,
                target: root.state.selected_target,
                profile_id: root.state.selected_id,
                host: host,
                user: user,
                identity: identity,
                password: password,
            });
        }
    }

    AboutDialog {
        show <=> StateBridge.state.show_about;
        version: root.state.version;
        z: 1000;
    }

    Notification {
        text <=> StateBridge.state.notification;
        is_error: root.state.notification_is_error;
        is_warning: root.state.notification_is_warning;
    }

    VerticalBox {
        spacing: 10px;

        HorizontalBox {
            padding: 0px;
            z: 2;
            version_text := Text {
                text: "Version:";
                horizontal-alignment: right;
                vertical-alignment: center;
                width: 55px;
            }

            version_combo := ComboBox {
                model: root.state.versions;
                enabled: !root.state.busy;
                horizontal-stretch: 1;

                selected(val) => {
                    StateBridge.version_changed(val);
                }
            }

            Switch {
                text: "Show pre-release versions";
                enabled: !root.state.busy;
                checked <=> StateBridge.state.show_rcs;

                toggled => {
                    StateBridge.show_rcs_toggled({
                        show_rcs: self.checked,
                        version: root.state.selected_version,
                    });
                }
            }

            ImageButton {
                source: @image-url("../assets/logo_no_frame.svg");
                image_height: 22px;
                image_width: 22px;

                clicked => {
                    StateBridge.state.show_about = true;
                }

                Tooltip {
                    text: @markdown("About Bouwer");
                }
            }
        }

        HorizontalBox {
            padding: 0px;
            z: 1;

            Text {
                text: "Profile:";
                horizontal-alignment: right;
                vertical-alignment: center;
                width: version_text.width;
            }

            profile_combo := EditableComboBox {
                text <=> StateBridge.state.search_text;
                placeholder-text: "Type to search...";
                current-index <=> StateBridge.state.current_highlighted_profile_index;
                enabled: !root.state.busy && root.state.versions.length > 0 && !root.state.profiles_fetch_failed;
                horizontal-stretch: 1;
                model: root.state.profiles;
                is-open: root.state.profiles.length > 0 && root.state.selected_id == "";
                item-height: Constants.autocomplete_element_height;

                edited(text) => {
                    StateBridge.profile_search_edited(text);
                }

                key_pressed(event) => {
                    return StateBridge.profile_search_key_pressed({
                        text: event.text,
                        index: root.state.current_highlighted_profile_index,
                        profiles: root.state.profiles,
                        version: root.state.selected_version,
                    });
                }

                selected(item) => {
                    StateBridge.profile_selected({
                        version: root.state.selected_version,
                        name: item,
                    });
                }
            }
        }

        HorizontalBox {
            padding: 0px;

            Rectangle {
                horizontal-stretch: 1;
            }

            download_button := Button {
                text: "Download image builder";
                enabled: !root.state.busy && root.state.selected_id != "" && !root.state.image_exists;
                primary: root.state.selected_id != "" && !root.state.image_exists;

                clicked => {
                    StateBridge.download_builder_requested({
                        version: root.state.selected_version,
                        target: root.state.selected_target,
                        profile_id: root.state.selected_id,
                    });
                }
            }

            load_preset_button := Button {
                text: "Load preset";
                enabled: !root.state.busy && !root.state.profiles_fetch_failed;

                clicked => {
                    StateBridge.load_preset_requested(root.state.selected_version);
                }
            }

            save_preset_button := Button {
                text: "Save preset";
                enabled: !root.state.busy && root.state.image_exists && !root.state.profiles_fetch_failed;

                clicked => {
                    StateBridge.save_preset_requested({
                        version: root.state.selected_version,
                        target: root.state.selected_target,
                        profile_id: root.state.selected_id,
                        extra_image_name: root.state.extra_image_name_text,
                        rootfs_size: root.state.rootfs_size_text.to-float(),
                        packages: root.state.packages_text,
                        disabled_services: root.state.disabled_services_text,
                        overlay_path: root.state.overlay_path_text,
                    });
                }
            }
        }

        Rectangle {
            background: Palette.control-background;
            border-width: 1px;
            border-color: Palette.border;
            border-radius: 4px;

            GridLayout {
                padding: 10px;
                spacing: 6px;

                Row {
                    Text {
                        text: "Model:";
                        width: 45px;
                        font-weight: 700;
                        horizontal-alignment: right;
                    }

                    Text {
                        text: root.state.selected_model;
                        wrap: word-wrap;
                    }
                }

                Row {
                    Text {
                        text: "ID:";
                        font-weight: 700;
                        horizontal-alignment: right;
                    }

                    Text {
                        text: root.state.selected_id;
                    }
                }

                Row {
                    Text {
                        text: "Target:";
                        font-weight: 700;
                        horizontal-alignment: right;
                    }

                    Text {
                        text: root.state.selected_target;
                    }
                }
            }
        }

        TabWidget {
            Tab {
                title: "General settings";

                VerticalBox {
                    padding: 0px;
                    padding-top: 10px;

                    HorizontalBox {
                        padding: 0px;
                        z: 100;

                        extra_image_label := Text {
                            text: "Extra image name:";
                            vertical-alignment: center;

                            Tooltip {
                                text: @markdown(
                                    "Extra name appended to the generated firmware image filenames"
                                );
                            }
                        }

                        extra_image_name := LineEdit {
                            text <=> StateBridge.state.extra_image_name_text;
                            enabled: !root.state.busy && root.state.image_exists;
                            placeholder_text: "none";
                            edited => {
                                root.recalculate_preview();
                            }
                        }
                    }

                    HorizontalBox {
                        padding: 0px;
                        z: 90;
                        alignment: space-between;

                        Text {
                            text: "Packages:";
                            vertical-alignment: center;

                            Tooltip {
                                text: @markdown(
                                    "Space-separated list of packages to include in the firmware"
                                );
                            }
                        }

                        ImageButton {
                            source: @image-url("../assets/router_from.svg");
                            enabled: !root.state.busy && root.state.image_exists;

                            clicked => {
                                root.state.show_device_dialog = true;
                            }

                            Tooltip {
                                text: @markdown("Fetch package list from a device via SSH");
                            }
                        }
                    }

                    packages_text := TextEdit {
                        text <=> StateBridge.state.packages_text;
                        enabled: !root.state.busy && root.state.image_exists;
                        min-height: 60px;
                        placeholder-text: "none";

                        edited(text) => {
                            StateBridge.packages_edited(text);
                            root.recalculate_preview();
                        }
                    }

                    Text {
                        text: "Removed default packages:";
                        horizontal-alignment: left;

                        Tooltip {
                            text: @markdown(
                                "Default packages that are excluded from the firmware"
                            );
                        }
                    }

                    removed_packages_text := TextEdit {
                        text: root.state.removed_packages_text;
                        enabled: !root.state.busy && root.state.image_exists;
                        min-height: 60px;
                        placeholder-text: "none";
                        read-only: true;
                    }
                }
            }

            Tab {
                title: "Advanced settings";

                VerticalBox {
                    padding: 0px;
                    padding-top: 10px;

                    HorizontalBox {
                        padding: 0px;
                        z: 100;

                        Text {
                            text: "RootFS size:";
                            vertical-alignment: center;

                            Tooltip {
                                text: @markdown("Size of the root filesystem in MiB");
                            }
                        }

                        rootfs_size := LineEdit {
                            text <=> root.state.rootfs_size_text;
                            enabled: !root.state.busy && root.state.image_exists;
                            input-type: InputType.number;
                            placeholder_text: "default";
                            edited(t) => {
                                root.recalculate_preview();
                            }
                        }
                    }

                    Text {
                        text: "Disabled services:";
                        horizontal-alignment: left;

                        Tooltip {
                            text: @markdown(
                                "Space-separated list of services to disable in the firmware"
                            );
                        }
                    }

                    disabled_services_text := TextEdit {
                        text <=> StateBridge.state.disabled_services_text;
                        enabled: !root.state.busy && root.state.image_exists;
                        min-height: 60px;
                        placeholder-text: "none";

                        edited => {
                            root.recalculate_preview();
                        }
                    }

                    HorizontalBox {
                        padding: 0px;
                        z: 80;

                        overlay_path_rect := Rectangle {
                            width: 100px;

                            overlay_path_label := Text {
                                text: "Overlay folder:";
                                horizontal-alignment: right;
                                vertical-alignment: center;
                                width: parent.width;

                                Tooltip {
                                    text: @markdown(
                                        "Path to the overlay folder which content will be added on top of the root filesystem"
                                    );
                                }
                            }
                        }

                        overlay_path_text := LineEdit {
                            text <=> StateBridge.state.overlay_path_text;
                            enabled: !root.state.busy && root.state.image_exists;
                            placeholder_text: "none";
                            read-only: false;
                        }

                        Button {
                            text: "Select folder";
                            enabled: !root.state.busy && root.state.image_exists;

                            clicked => {
                                StateBridge.select_overlay_folder_requested();
                            }
                        }
                    }

                    HorizontalBox {
                        padding: 0px;
                        z: 70;

                        build_path_rect := Rectangle {
                            width: 100px;

                            build_path_label := Text {
                                text: "Build folder:";
                                horizontal-alignment: right;
                                vertical-alignment: center;
                                width: parent.width;

                                Tooltip {
                                    text: @markdown(
                                        "Path to the build folder where the firmware images will be built"
                                    );
                                }
                            }
                        }

                        build_path_text := LineEdit {
                            text <=> StateBridge.state.build_path_text;
                            enabled: !root.state.busy;
                            placeholder_text: "none";
                            read-only: false;

                            edited(text) => {
                                StateBridge.build_path_edited(text);
                            }
                        }

                        Button {
                            text: "Select folder";
                            enabled: !root.state.busy;

                            clicked => {
                                StateBridge.select_build_folder_requested();
                            }
                        }
                    }
                }
            }

            Tab {
                title: "Build details";
                VerticalBox {
                    padding: 0px;
                    padding-top: 10px;

                    Text {
                        text: "Build command:";
                        horizontal-alignment: left;

                        Tooltip {
                            text: @markdown(
                                "Build command that will be passed to the image builder"
                            );
                        }
                    }

                    TextEdit {
                        text: root.state.build_command_preview;
                        read-only: true;
                        font-family: "monospace";
                        wrap: word-wrap;
                    }
                }
            }

            Tab {
                title: "Image builders";
                VerticalBox {
                    padding: 0px;
                    padding-top: 10px;

                    HorizontalBox {
                        padding: 0px;

                        Text {
                            text: "Downloaded image builders:";
                            vertical-alignment: center;
                        }

                        Rectangle {
                            horizontal-stretch: 1;
                        }

                        ImageButton {
                            source: @image-url("../assets/refresh.svg");
                            enabled: !root.state.busy && root.state.image_exists;

                            clicked => {
                                StateBridge.refresh_builders_requested();
                            }

                            Tooltip {
                                text: @markdown("Refresh list of downloaded image builders");
                            }
                        }
                    }

                    ImageBuilderList {
                        builders: root.state.downloaded_builders;
                        busy: root.state.busy;

                        delete_builder(tag) => {
                            StateBridge.delete_builder_requested({
                                tag: tag,
                                version: root.state.selected_version,
                                target: root.state.selected_target,
                                profile_id: root.state.selected_id,
                            });
                        }
                    }
                }
            }
        }

        HorizontalBox {
            padding: 0px;
            spacing: 10px;

            Rectangle {
                horizontal-stretch: 1;
            }

            Button {
                text: "Open build folder";
                enabled: !root.state.busy && root.state.image_exists;

                clicked => {
                    StateBridge.open_build_folder_requested(root.state.selected_target);
                }
            }

            build_button := Button {
                text: "Build firmware";
                primary: true;
                enabled: !root.state.busy && root.state.image_exists && root.state.packages_text != "";

                clicked => {
                    StateBridge.build_requested({
                        version: root.state.selected_version,
                        target: root.state.selected_target,
                        profile_id: root.state.selected_id,
                        extra_image_name: root.state.extra_image_name_text,
                        rootfs_size: root.state.rootfs_size_text.to-float(),
                        packages: root.state.packages_text,
                        disabled_services: root.state.disabled_services_text,
                        overlay_path: root.state.overlay_path_text,
                    });
                }
            }
        }

        Rectangle {
            background: Palette.control-background;
            border-width: 1px;
            border-color: Palette.border;
            border-radius: 4px;

            HorizontalBox {
                padding-top: 6px;
                padding-bottom: 6px;
                padding-left: 10px;
                padding-right: 10px;

                status_text := Text {
                    text: "Ready";
                    horizontal-alignment: left;
                    vertical-alignment: center;

                    states [
                        fetch_failed when StateBridge.state.profiles_fetch_failed: {
                            text: "Failed to fetch profiles";
                        }

                        no_profile when StateBridge.state.selected_id == "": {
                            text: "Select profile";
                        }

                        missing_builder when !StateBridge.state.image_exists && StateBridge.state.status_text == "": {
                            text: "Missing image builder";
                        }

                        custom when StateBridge.state.status_text != "": {
                            text: StateBridge.state.status_text;
                        }
                    ]
                }

                VerticalBox {
                    width: 50%;

                    ProgressIndicator {
                        height: 10px;
                        progress: root.state.progress_value;
                        opacity: 0.0;
                        indeterminate: root.state.progress_value == 0.0 && root.state.progress_visible;

                        states [
                            visible_state when root.state.progress_visible: {
                                opacity: 1.0;

                                in {
                                    animate opacity { duration: 250ms; }
                                }

                                out {
                                    animate opacity { duration: 250ms; }
                                }
                            }
                        ]
                    }
                }
            }
        }
    }
}
