// Copyright (C) 2026 George Sapkin
//
// SPDX-License-Identifier: GPL-3.0-only

import { HorizontalBox, Palette, VerticalBox } from "std-widgets.slint";

export component Notification inherits Rectangle {
    in-out property <string> text: "";
    in property <duration> fade_duration: 300ms;
    in property <bool> is_error: false;
    in property <bool> is_warning: false;

    height: 80px;
    opacity: 0.0;
    clip: true;
    y: -80px;
    z: 2;

    VerticalBox {
        padding-bottom: 20px;

        inner_notification_rect := Rectangle {
            background: transparent;
            border-color: transparent;
            border-width: 1px;
            border-radius: 4px;
            drop-shadow-blur: 16px;
            drop-shadow-offset-y: 8px;
            drop-shadow-color: Palette.color-scheme == ColorScheme.dark ? rgba(0, 0, 0, 0.26) : rgba(0, 0, 0, 0.14);

            TouchArea {
                width: 100%;
                height: 100%;
            }

            HorizontalBox {
                padding-left: 15px;
                padding-right: 7px;
                notification_text := Text {
                    text: root.text;
                    color: transparent;
                    vertical-alignment: center;
                    font-size: 14px;
                    horizontal-stretch: 1;
                }

                VerticalBox {
                    Rectangle {
                        height: close_icon.height;
                        width: close_icon.width;

                        TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                root.text = "";
                            }
                        }

                        close_icon := Path {
                            commands: "M 2 2 L 12 12 M 12 2 L 2 12";
                            stroke: transparent;
                            stroke-width: 1px;
                            height: 11px;
                            width: 11px;
                        }
                    }
                }
            }
        }
    }

    states [
        error when root.text != "" && root.is_error: {
            inner_notification_rect.background: #ffebee;
            inner_notification_rect.border-color: #f44336;
            notification_text.color: #b71c1c;
            close_icon.stroke: #b71c1c;
            opacity: 1.0;
            y: 0px;
            in {
                animate opacity, y, inner_notification_rect.background, inner_notification_rect.border-color, notification_text.color, close_icon.stroke {
                    duration: fade_duration;
                    easing: ease-in-out-elastic;
                }
            }
            out {
                animate opacity, y, inner_notification_rect.background, inner_notification_rect.border-color, notification_text.color, close_icon.stroke {
                    duration: fade_duration;
                    easing: ease-in-out-elastic;
                }
            }
        }
        warning when root.text != "" && root.is_warning: {
            inner_notification_rect.background: #fff9c4;
            inner_notification_rect.border-color: #fbc02d;
            notification_text.color: #f57f17;
            close_icon.stroke: #f57f17;
            opacity: 1.0;
            y: 0px;
            in {
                animate opacity, y, inner_notification_rect.background, inner_notification_rect.border-color, notification_text.color, close_icon.stroke {
                    duration: fade_duration;
                    easing: ease-out;
                }
            }
            out {
                animate opacity, y, inner_notification_rect.background, inner_notification_rect.border-color, notification_text.color, close_icon.stroke {
                    duration: fade_duration;
                    easing: ease-out;
                }
            }
        }
        info when root.text != "": {
            inner_notification_rect.background: #e1f5fe;
            inner_notification_rect.border-color: #03a9f4;
            notification_text.color: #01579b;
            close_icon.stroke: #01579b;
            opacity: 1.0;
            y: 0px;
            in {
                animate opacity, y, inner_notification_rect.background, inner_notification_rect.border-color, notification_text.color, close_icon.stroke {
                    duration: fade_duration;
                    easing: ease-out;
                }
            }
            out {
                animate opacity, y, inner_notification_rect.background, inner_notification_rect.border-color, notification_text.color, close_icon.stroke {
                    duration: fade_duration;
                    easing: ease-out;
                }
            }
        }
    ]
}
