name: Reusable Build
on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libfontconfig1-dev libxkbcommon-dev libwayland-dev libx11-dev upx-ucl

      - name: Install dependencies
        if: matrix.os == 'windows-latest'
        run: choco install upx

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Enable Rust cache
        uses: swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build --release
        env:
          RUSTFLAGS: ${{ matrix.os == 'windows-latest' && '-C target-feature=+crt-static' || '' }}

      - name: Compress binary
        if: matrix.os == 'ubuntu-latest'
        run: upx --lzma --best --filter=0 target/release/bouwer

      - name: Compress binary
        if: matrix.os == 'windows-latest'
        run: upx --lzma --best --filter=0 target/release/bouwer.exe

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: bouwer-${{ matrix.os }}
          path: |
            target/release/bouwer
            target/release/bouwer.exe
          if-no-files-found: error
